name = "xydesk-admin"
main = "./worker.js"
compatibility_date = "2026-08-17"

routes = [
  { pattern = "admin.xydesk.my.id", custom_domain = true }
]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
