[package]
name = "audio-check"
version = "0.0.0"
edition = "2021"
publish = false
[dependencies]
anyhow = "1"
[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.61", features = ["Win32_Media_Audio", "Win32_Media_Audio_Endpoints", "Win32_System_Com", "Win32_System_Com_StructuredStorage", "Win32_System_Variant", "Win32_UI_Shell_PropertiesSystem"] }
[profile.dev]
debug = 0
