import {useEffect,useRef} from 'react';
import type {PointerEvent} from 'react';
function MouseIcon({right=false}:{right?:boolean}){return <svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><rect x="5" y="2" width="14" height="20" rx="7"/><path d="M12 2v8M5 10h14"/><path d={right?'M13 4a5 5 0 0 1 4 5h-4z':'M11 4a5 5 0 0 0-4 5h4z'} fill="currentColor" stroke="none"/></svg>;}
export function MouseHud({onMouse,onMouseClick,onScroll,onWindows,onCenter,onSwitch,trackpad}:{onMouse:(e:PointerEvent<HTMLButtonElement>,button:number,down:boolean)=>void;onMouseClick:(button:number)=>void;onScroll:(delta:number)=>void;onWindows:(key:string,down:boolean)=>void;onCenter:()=>void;onSwitch:()=>void;trackpad:boolean}){
 const repeat=useRef(new Map<number,ReturnType<typeof setInterval>>());
 const clear=(id:number)=>{const timer=repeat.current.get(id);if(timer!==undefined){clearInterval(timer);repeat.current.delete(id);}};
 const scrollRef=useRef(onScroll);scrollRef.current=onScroll;
 useEffect(()=>{const reset=()=>{for(const id of repeat.current.keys())clear(id);};const visibility=()=>{if(document.hidden)reset();};window.addEventListener('blur',reset);document.addEventListener('visibilitychange',visibility);return()=>{reset();window.removeEventListener('blur',reset);document.removeEventListener('visibilitychange',visibility);};},[]);
 return <div className="hud-mouse" aria-label="Kontrol mouse">
 {[0,1].map(button=><button key={button} type="button" className="hud-icon-btn" aria-label={button?'Klik kanan':'Klik kiri'} title={button?'Klik kanan':'Klik kiri — tahan untuk drag'} onPointerDown={e=>onMouse(e,button,true)} onPointerUp={e=>onMouse(e,button,false)} onPointerCancel={e=>onMouse(e,button,false)} onLostPointerCapture={e=>onMouse(e,button,false)} onContextMenu={e=>e.preventDefault()} onClick={e=>{if(e.detail===0)onMouseClick(button);}}><MouseIcon right={button===1}/></button>)}
 {[120,-120].map(delta=><button key={delta} type="button" className="hud-icon-btn" aria-label={delta>0?'Scroll atas':'Scroll bawah'} onPointerDown={e=>{e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);clear(e.pointerId);scrollRef.current(delta);repeat.current.set(e.pointerId,setInterval(()=>scrollRef.current(delta),100));}} onPointerUp={e=>clear(e.pointerId)} onPointerCancel={e=>clear(e.pointerId)} onLostPointerCapture={e=>clear(e.pointerId)} onClick={e=>{if(e.detail===0)scrollRef.current(delta);}}><svg viewBox="0 0 24 24" width="23" height="23" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d={delta>0?'m6 14 6-6 6 6':'m6 10 6 6 6-6'}/></svg></button>)}
 <button type="button" className="hud-icon-btn" aria-label="Tombol Windows" onPointerDown={e=>{e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);onWindows(String(e.pointerId),true);}} onPointerUp={e=>onWindows(String(e.pointerId),false)} onPointerCancel={e=>onWindows(String(e.pointerId),false)} onLostPointerCapture={e=>onWindows(String(e.pointerId),false)} onClick={e=>{if(e.detail===0){onWindows('keyboard',true);onWindows('keyboard',false);}}}><svg viewBox="0 0 24 24" width="22" height="22" fill="currentColor" aria-hidden="true"><path d="M3 3h8v8H3zm10 0h8v8h-8zM3 13h8v8H3zm10 0h8v8h-8z"/></svg></button>
 <button type="button" className="hud-icon-btn" aria-label="Switch langsung / trackpad" aria-pressed={trackpad} onClick={onSwitch} title={trackpad?'Trackpad aktif':'Sentuh langsung aktif'}>⇄</button>
 <button type="button" className="hud-icon-btn" aria-label="Temukan panah" onClick={onCenter}>⌖</button>
 </div>;
}
